#!/usr/bin/env python3
"""
Script to populate the PostgreSQL database with fake candidates.
Usage: python3 populate_candidates.py
"""

import psycopg2
from psycopg2.extras import RealDictCursor
import random
import string
from datetime import datetime

# Database connection string
DATABASE_URL = "postgresql://neondb_owner:npg_EFWkTr60tGzY@ep-cold-smoke-ahfq9uwr-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"

# Sample data for generating fake candidates
FIRST_NAMES = [
    "James",
    "Mary",
    "John",
    "Patricia",
    "Robert",
    "Jennifer",
    "Michael",
    "Linda",
    "William",
    "Elizabeth",
    "David",
    "Barbara",
    "Richard",
    "Susan",
    "Joseph",
    "Jessica",
    "Thomas",
    "Sarah",
    "Charles",
    "Karen",
    "Christopher",
    "Nancy",
    "Daniel",
    "Lisa",
    "Matthew",
    "Betty",
    "Anthony",
    "Margaret",
    "Mark",
    "Sandra",
    "Donald",
    "Ashley",
    "Steven",
    "Kimberly",
    "Paul",
    "Emily",
    "Andrew",
    "Donna",
    "Joshua",
    "Michelle",
    "Kenneth",
    "Dorothy",
    "Kevin",
    "Carol",
    "Brian",
    "Amanda",
    "George",
    "Melissa",
    "Edward",
    "Deborah",
    "Ronald",
    "Stephanie",
    "Timothy",
    "Rebecca",
    "Jason",
    "Sharon",
    "Jeffrey",
    "Laura",
    "Ryan",
    "Cynthia",
    "Jacob",
    "Kathleen",
    "Gary",
    "Amy",
    "Nicholas",
    "Shirley",
    "Eric",
    "Angela",
    "Jonathan",
    "Helen",
    "Stephen",
    "Anna",
    "Larry",
    "Brenda",
    "Justin",
    "Pamela",
    "Scott",
    "Nicole",
    "Brandon",
    "Emma",
    "Benjamin",
    "Samantha",
    "Samuel",
    "Katherine",
    "Gregory",
    "Christine",
    "Frank",
    "Debra",
    "Alexander",
    "Rachel",
    "Raymond",
    "Catherine",
    "Patrick",
    "Carolyn",
    "Jack",
    "Janet",
    "Dennis",
    "Ruth",
    "Jerry",
    "Maria",
    "Tyler",
    "Heather",
    "Aaron",
    "Diane",
    "Jose",
    "Virginia",
    "Adam",
    "Julie",
    "Henry",
    "Joyce",
    "Nathan",
    "Victoria",
    "Douglas",
    "Olivia",
    "Zachary",
    "Kelly",
    "Peter",
    "Christina",
    "Kyle",
    "Lauren",
    "Walter",
    "Joan",
    "Ethan",
    "Evelyn",
    "Jeremy",
    "Judith",
    "Harold",
    "Megan",
    "Keith",
    "Cheryl",
    "Christian",
    "Andrea",
    "Roger",
    "Hannah",
    "Noah",
    "Martha",
    "Gerald",
    "Jacqueline",
    "Carl",
    "Frances",
    "Terry",
    "Gloria",
    "Sean",
    "Ann",
    "Austin",
    "Teresa",
    "Arthur",
    "Kathryn",
    "Lawrence",
    "Sara",
    "Jesse",
    "Janice",
    "Dylan",
    "Jean",
    "Bryan",
    "Alice",
    "Joe",
    "Madison",
    "Jordan",
    "Doris",
    "Billy",
    "Abigail",
    "Bruce",
    "Julia",
    "Albert",
    "Judy",
    "Willie",
    "Grace",
    "Gabriel",
    "Denise",
    "Logan",
    "Amber",
    "Alan",
    "Marilyn",
    "Juan",
    "Beverly",
    "Wayne",
    "Danielle",
    "Louis",
    "Theresa",
    "Elijah",
    "Sophia",
    "Randy",
    "Marie",
    "Vincent",
    "Diana",
    "Russell",
    "Brittany",
    "Ralph",
    "Natalie",
    "Roy",
    "Isabella",
    "Eugene",
    "Charlotte",
    "Bobby",
    "Rose",
    "Mason",
    "Alexis",
    "Philip",
    "Kayla",
    "Mary",
    "Lori",
]

LAST_NAMES = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Rivera",
    "Campbell",
    "Mitchell",
    "Carter",
    "Roberts",
    "Gomez",
    "Phillips",
    "Evans",
    "Turner",
    "Diaz",
    "Parker",
    "Cruz",
    "Edwards",
    "Collins",
    "Reyes",
    "Stewart",
    "Morris",
    "Morales",
    "Murphy",
    "Cook",
    "Rogers",
    "Gutierrez",
    "Ortiz",
    "Morgan",
    "Cooper",
    "Peterson",
    "Bailey",
    "Reed",
    "Kelly",
    "Howard",
    "Ramos",
    "Kim",
    "Cox",
    "Ward",
    "Richardson",
    "Watson",
    "Brooks",
    "Chavez",
    "Wood",
    "James",
    "Bennett",
    "Gray",
    "Mendoza",
    "Ruiz",
    "Hughes",
    "Price",
    "Alvarez",
    "Castillo",
    "Sanders",
    "Patel",
    "Myers",
    "Long",
    "Ross",
    "Foster",
    "Jimenez",
    "Powell",
    "Jenkins",
    "Perry",
    "Russell",
    "Sullivan",
    "Bell",
    "Coleman",
    "Butler",
    "Henderson",
    "Barnes",
    "Gonzales",
    "Fisher",
    "Vasquez",
    "Simmons",
    "Romero",
    "Jordan",
    "Patterson",
    "Alexander",
    "Hamilton",
    "Graham",
    "Reynolds",
    "Griffin",
    "Wallace",
    "Moreno",
    "West",
    "Cole",
    "Hayes",
    "Bryant",
    "Herrera",
    "Gibson",
    "Ellis",
    "Tran",
    "Medina",
    "Aguilar",
    "Stevens",
    "Murray",
    "Ford",
    "Castro",
    "Marshall",
    "Owens",
    "Harrison",
    "Fernandez",
    "Woods",
    "Washington",
    "Kennedy",
    "Wells",
    "Vargas",
    "Henry",
    "Chen",
    "Freeman",
    "Webb",
    "Tucker",
    "Guzman",
    "Burns",
    "Crawford",
    "Olson",
    "Simpson",
    "Porter",
    "Hunter",
    "Gordon",
    "Mendez",
    "Silva",
    "Shaw",
    "Snyder",
    "Mason",
    "Dixon",
    "Munoz",
    "Hunt",
    "Hicks",
    "Holmes",
    "Palmer",
    "Wagner",
    "Black",
    "Robertson",
    "Boyd",
    "Rose",
    "Stone",
    "Salazar",
    "Fox",
    "Warren",
    "Mills",
    "Meyer",
    "Rice",
    "Schmidt",
    "Garza",
    "Daniels",
    "Ferguson",
    "Nichols",
    "Stephens",
    "Soto",
    "Weaver",
    "Ryan",
    "Gardner",
    "Payne",
    "Grant",
    "Dunn",
    "Kelley",
    "Spencer",
    "Hawkins",
    "Arnold",
    "Pierce",
    "Vazquez",
    "Hansen",
    "Peters",
    "Santos",
    "Hart",
    "Bradley",
    "Knight",
    "Elliott",
    "Cunningham",
    "Duncan",
    "Armstrong",
    "Hudson",
    "Carroll",
    "Lane",
    "Riley",
    "Andrews",
    "Alvarado",
    "Ray",
    "Delgado",
    "Berry",
    "Perkins",
    "Hoffman",
    "Johnston",
    "Matthews",
    "Pena",
    "Richards",
    "Contreras",
    "Caldwell",
    "Sims",
    "Norman",
    "Valdez",
]

ROLES = [
    "Software Engineer",
    "Product Manager",
    "Data Scientist",
    "UX Designer",
    "DevOps Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Mobile Developer",
    "QA Engineer",
    "Technical Lead",
    "Engineering Manager",
    "CTO",
    "VP of Engineering",
    "Machine Learning Engineer",
    "Data Analyst",
    "Business Analyst",
    "Project Manager",
    "Scrum Master",
    "UI Designer",
    "Graphic Designer",
    "Marketing Manager",
    "Sales Manager",
    "Account Executive",
    "Customer Success Manager",
    "HR Manager",
    "Recruiter",
    "Financial Analyst",
    "Accountant",
    "Operations Manager",
    "Office Manager",
    "Content Strategist",
    "SEO Specialist",
    "Social Media Manager",
    "Copywriter",
    "Legal Counsel",
    "Paralegal",
    "Research Scientist",
    "Biologist",
    "Chemist",
    "Physicist",
    "Doctor",
    "Nurse",
    "Physician Assistant",
    "Physical Therapist",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Civil Engineer",
    "Chemical Engineer",
    "Architect",
    "Interior Designer",
    "Real Estate Agent",
    "Insurance Agent",
    "Teacher",
    "Professor",
    "Librarian",
    "Journalist",
    "Editor",
    "Writer",
    "Photographer",
    "Videographer",
    "Musician",
    "Artist",
    "Chef",
    "Restaurant Manager",
    "Hotel Manager",
    "Event Planner",
    "Consultant",
    "Analyst",
    "Strategist",
    "Director",
    "Coordinator",
    "Specialist",
    "Associate",
    "Intern",
    "Trainee",
    "Representative",
    "Agent",
    "Officer",
    "Administrator",
    "Supervisor",
    "Technician",
    "Specialist",
    "Expert",
    "Professional",
    "Adviser",
    "Consultant",
    "Partner",
    "Founder",
    "CEO",
    "COO",
    "CFO",
    "CMO",
    "CHRO",
]

COMPANIES = [
    "Google",
    "Microsoft",
    "Apple",
    "Amazon",
    "Meta",
    "Netflix",
    "Tesla",
    "SpaceX",
    "Stripe",
    "Airbnb",
    "Uber",
    "Lyft",
    "Spotify",
    "Twitter",
    "LinkedIn",
    "Adobe",
    "Salesforce",
    "Oracle",
    "IBM",
    "Intel",
    "NVIDIA",
    "AMD",
    "Cisco",
    "Dell",
    "HP",
    "Lenovo",
    "Samsung",
    "Sony",
    "Panasonic",
    "LG",
    "Toshiba",
    "Asus",
    "Acer",
    "Dell Technologies",
    "VMware",
    "Red Hat",
    "Slack",
    "Zoom",
    "Teams",
    "Notion",
    "Figma",
    "Sketch",
    "InVision",
    "Canva",
    "Shopify",
    "Square",
    "PayPal",
    "Venmo",
    "Robinhood",
    "Coinbase",
    "Binance",
    "Kraken",
    "Gemini",
    "Plaid",
    "Stripe",
    "Twilio",
    "SendGrid",
    "Mailchimp",
    "HubSpot",
    "Marketo",
    "Pardot",
    "Zapier",
    "IFTTT",
    "Intuit",
    "QuickBooks",
    "TurboTax",
    "H&R Block",
    "Deloitte",
    "KPMG",
    "PwC",
    "EY",
    "McKinsey",
    "BCG",
    "Bain",
    "Accenture",
    "IBM Consulting",
    "Capgemini",
    "Infosys",
    "TCS",
    "Wipro",
    "Cognizant",
    "EPAM",
    "Luxoft",
    "Globant",
    "Endava",
    "Softtek",
    "Softvision",
    "ThoughtWorks",
    "Pivotal",
    "HashiCorp",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitLab",
    "GitHub",
    "Bitbucket",
    "Atlassian",
    "Jira",
    "Confluence",
    "Trello",
    "Asana",
    "Monday.com",
    "ClickUp",
    "Notion",
    "Coda",
    "Airtable",
    "Smartsheet",
    "Wrike",
    "Basecamp",
    "Salesforce",
    "HubSpot",
    "Zoho",
    "Pipedrive",
    "Freshworks",
    "Zendesk",
    "Intercom",
    "Drift",
    "Mailchimp",
    "Constant Contact",
    "Campaign Monitor",
    "Klaviyo",
    "ActiveCampaign",
    "ConvertKit",
    "Drip",
    "Sendinblue",
    "Shopify",
    "WooCommerce",
    "Magento",
    "BigCommerce",
    "Volusion",
    "3dcart",
    "Squarespace",
    "Wix",
    "Weebly",
    "WordPress",
    "Drupal",
    "Joomla",
    "Ghost",
    "Medium",
    "Substack",
    "Patreon",
    "Kickstarter",
    "Indiegogo",
    "GoFundMe",
    "Patreon",
    "OnlyFans",
    "Twitch",
    "YouTube",
    "TikTok",
    "Instagram",
    "Facebook",
    "Snapchat",
    "Pinterest",
    "Reddit",
    "Quora",
    "Stack Overflow",
    "GitHub",
]

LOCATIONS = [
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Houston, TX",
    "Phoenix, AZ",
    "Philadelphia, PA",
    "San Antonio, TX",
    "San Diego, CA",
    "Dallas, TX",
    "San Jose, CA",
    "Austin, TX",
    "Jacksonville, FL",
    "Fort Worth, TX",
    "Columbus, OH",
    "Charlotte, NC",
    "Indianapolis, IN",
    "San Francisco, CA",
    "Seattle, WA",
    "Denver, CO",
    "Washington, DC",
    "Boston, MA",
    "El Paso, TX",
    "Nashville, TN",
    "Detroit, MI",
    "Oklahoma City, OK",
    "Portland, OR",
    "Las Vegas, NV",
    "Louisville, KY",
    "Baltimore, MD",
    "Milwaukee, WI",
    "Albuquerque, NM",
    "Tucson, AZ",
    "Fresno, CA",
    "Sacramento, CA",
    "Mesa, AZ",
    "Kansas City, MO",
    "Atlanta, GA",
    "Long Beach, CA",
    "Colorado Springs, CO",
    "Raleigh, NC",
    "Miami, FL",
    "Virginia Beach, VA",
    "Omaha, NE",
    "Oakland, CA",
    "Minneapolis, MN",
    "Tulsa, OK",
    "Arlington, TX",
    "New Orleans, LA",
    "Wichita, KS",
    "Cleveland, OH",
    "Tampa, FL",
    "Bakersfield, CA",
    "Aurora, CO",
    "Anaheim, CA",
    "Honolulu, HI",
    "Santa Ana, CA",
    "Riverside, CA",
    "Corpus Christi, TX",
    "Lexington, KY",
    "Stockton, CA",
    "Henderson, NV",
    "Saint Paul, MN",
    "St. Louis, MO",
    "Cincinnati, OH",
    "Pittsburgh, PA",
    "Greensboro, NC",
    "Anchorage, AK",
    "Plano, TX",
    "Lincoln, NE",
    "Orlando, FL",
    "Irvine, CA",
    "Newark, NJ",
    "Durham, NC",
    "Chula Vista, CA",
    "Toledo, OH",
    "Fort Wayne, IN",
    "St. Petersburg, FL",
    "Laredo, TX",
    "Jersey City, NJ",
    "Chandler, AZ",
    "Madison, WI",
    "Lubbock, TX",
    "Scottsdale, AZ",
    "Reno, NV",
    "Buffalo, NY",
    "Gilbert, AZ",
    "Glendale, AZ",
    "North Las Vegas, NV",
    "Winston-Salem, NC",
    "Chesapeake, VA",
    "Norfolk, VA",
    "Fremont, CA",
    "Garland, TX",
    "Irving, TX",
    "Hialeah, FL",
    "Richmond, VA",
    "Boise, ID",
    "Spokane, WA",
    "Baton Rouge, LA",
    "Des Moines, IA",
    "Tacoma, WA",
    "San Bernardino, CA",
    "Modesto, CA",
    "Fontana, CA",
    "Santa Clarita, CA",
    "Birmingham, AL",
    "Oxnard, CA",
    "Fayetteville, NC",
    "Moreno Valley, CA",
    "Rochester, NY",
    "London, UK",
    "Paris, France",
    "Berlin, Germany",
    "Madrid, Spain",
    "Rome, Italy",
    "Amsterdam, Netherlands",
    "Vienna, Austria",
    "Zurich, Switzerland",
    "Stockholm, Sweden",
    "Oslo, Norway",
    "Copenhagen, Denmark",
    "Helsinki, Finland",
    "Dublin, Ireland",
    "Brussels, Belgium",
    "Prague, Czech Republic",
    "Warsaw, Poland",
    "Budapest, Hungary",
    "Bucharest, Romania",
    "Sofia, Bulgaria",
    "Athens, Greece",
    "Lisbon, Portugal",
    "Barcelona, Spain",
    "Milan, Italy",
    "Munich, Germany",
    "Hamburg, Germany",
    "Frankfurt, Germany",
    "Düsseldorf, Germany",
    "Stuttgart, Germany",
    "Cologne, Germany",
    "Nuremberg, Germany",
    "Toronto, Canada",
    "Vancouver, Canada",
    "Montreal, Canada",
    "Calgary, Canada",
    "Ottawa, Canada",
    "Edmonton, Canada",
    "Quebec City, Canada",
    "Winnipeg, Canada",
    "Halifax, Canada",
    "Victoria, Canada",
    "Sydney, Australia",
    "Melbourne, Australia",
    "Brisbane, Australia",
    "Perth, Australia",
    "Adelaide, Australia",
    "Auckland, New Zealand",
    "Wellington, New Zealand",
    "Christchurch, New Zealand",
    "Dunedin, New Zealand",
    "Hamilton, New Zealand",
    "Singapore",
    "Hong Kong",
    "Tokyo, Japan",
    "Seoul, South Korea",
    "Beijing, China",
    "Shanghai, China",
    "Shenzhen, China",
    "Bangkok, Thailand",
    "Jakarta, Indonesia",
    "Kuala Lumpur, Malaysia",
    "Manila, Philippines",
    "Ho Chi Minh City, Vietnam",
    "Hanoi, Vietnam",
    "Mumbai, India",
    "Delhi, India",
    "Bangalore, India",
    "Hyderabad, India",
    "Chennai, India",
    "Kolkata, India",
    "Pune, India",
    "Dubai, UAE",
    "Abu Dhabi, UAE",
    "Riyadh, Saudi Arabia",
    "Jeddah, Saudi Arabia",
    "Doha, Qatar",
    "Kuwait City, Kuwait",
    "Manama, Bahrain",
    "Muscat, Oman",
    "Tel Aviv, Israel",
    "Jerusalem, Israel",
    "Istanbul, Turkey",
    "Ankara, Turkey",
    "Izmir, Turkey",
    "Cairo, Egypt",
    "Alexandria, Egypt",
    "Johannesburg, South Africa",
    "Cape Town, South Africa",
    "Durban, South Africa",
    "Pretoria, South Africa",
    "Port Elizabeth, South Africa",
    "São Paulo, Brazil",
    "Rio de Janeiro, Brazil",
    "Brasília, Brazil",
    "Salvador, Brazil",
    "Fortaleza, Brazil",
    "Buenos Aires, Argentina",
    "Córdoba, Argentina",
    "Rosario, Argentina",
    "Mendoza, Argentina",
    "La Plata, Argentina",
    "Santiago, Chile",
    "Valparaíso, Chile",
    "Concepción, Chile",
    "Montevideo, Uruguay",
    "Asunción, Paraguay",
    "Lima, Peru",
    "Arequipa, Peru",
    "Trujillo, Peru",
    "Bogotá, Colombia",
    "Medellín, Colombia",
    "Cali, Colombia",
    "Barranquilla, Colombia",
    "Caracas, Venezuela",
    "Maracaibo, Venezuela",
    "Valencia, Venezuela",
    "Mexico City, Mexico",
    "Guadalajara, Mexico",
    "Monterrey, Mexico",
    "Puebla, Mexico",
    "Tijuana, Mexico",
    "Panama City, Panama",
    "San José, Costa Rica",
    "Guatemala City, Guatemala",
    "San Salvador, El Salvador",
    "Tegucigalpa, Honduras",
    "Managua, Nicaragua",
    "San Juan, Puerto Rico",
    "Santo Domingo, Dominican Republic",
    "Havana, Cuba",
    "Port-au-Prince, Haiti",
    "Kingston, Jamaica",
    "Nassau, Bahamas",
    "Bridgetown, Barbados",
    "Port of Spain, Trinidad and Tobago",
    "St. John's, Antigua and Barbuda",
]


def generate_linkedin_url(first_name, last_name):
    """Generate a realistic LinkedIn URL"""
    base = "https://linkedin.com/in/"
    # Random variations
    variations = [
        f"{first_name.lower()}-{last_name.lower()}",
        f"{first_name.lower()[0]}{last_name.lower()}",
        f"{first_name.lower()}-{last_name.lower()}-{random.randint(1, 999)}",
        f"{first_name.lower()}{last_name.lower()[0]}",
        f"{first_name.lower()}.{last_name.lower()}",
        f"{last_name.lower()}{first_name.lower()[0]}",
        f"{first_name.lower()}-{last_name.lower()}-professional",
        f"{first_name.lower()}_{last_name.lower()}",
        f"{first_name.lower()}{last_name.lower()}{random.randint(1, 99)}",
    ]
    return base + random.choice(variations)


def generate_candidate():
    """Generate a single fake candidate"""
    first_name = random.choice(FIRST_NAMES)
    last_name = random.choice(LAST_NAMES)
    name = f"{first_name} {last_name}"

    return {
        "name": name,
        "role": random.choice(ROLES),
        "company": random.choice(COMPANIES),
        "location": random.choice(LOCATIONS),
        "linkedin_url": generate_linkedin_url(first_name, last_name),
        "status": random.choice(
            ["qualified", "contacted", "responded", "not_interested"]
        ),
        "email_chain_status": random.choice(
            ["not_started", "initial_sent", "conversation_active", "completed"]
        ),
    }


def populate_database(num_candidates=100):
    """Populate the database with fake candidates"""
    print(f"Connecting to database...")

    conn = None
    try:
        # Connect to the database
        conn = psycopg2.connect(DATABASE_URL)
        cursor = conn.cursor(cursor_factory=RealDictCursor)

        # Check current count
        cursor.execute("SELECT COUNT(*) as count FROM candidates")
        current_count = cursor.fetchone()["count"]
        print(f"Current candidates in database: {current_count}")

        # Generate and insert candidates
        candidates = []
        for i in range(num_candidates):
            candidate = generate_candidate()
            candidates.append(candidate)

        # Insert candidates in batches
        inserted = 0
        for candidate in candidates:
            try:
                cursor.execute(
                    """
                    INSERT INTO candidates (name, role, company, location, linkedin_url, status, email_chain_status)
                    VALUES (%(name)s, %(role)s, %(company)s, %(location)s, %(linkedin_url)s, %(status)s, %(email_chain_status)s)
                    RETURNING id
                    """,
                    candidate,
                )
                result = cursor.fetchone()
                if result:
                    inserted += 1
                    if inserted % 10 == 0:
                        print(f"Inserted {inserted}/{num_candidates} candidates...")
            except Exception as e:
                print(f"Error inserting candidate {candidate['name']}: {e}")
                continue

        conn.commit()

        # Get final count
        cursor.execute("SELECT COUNT(*) as count FROM candidates")
        final_count = cursor.fetchone()["count"]

        print(f"\n✅ Successfully populated database!")
        print(f"   - Inserted: {inserted} new candidates")
        print(f"   - Total candidates in database: {final_count}")

        # Show sample of data
        cursor.execute("SELECT * FROM candidates ORDER BY created_at DESC LIMIT 5")
        recent = cursor.fetchall()
        print(f"\n📋 Sample of recently added candidates:")
        for i, candidate in enumerate(recent, 1):
            print(
                f"   {i}. {candidate['name']} - {candidate['role']} at {candidate['company']} ({candidate['location']})"
            )

    except Exception as e:
        print(f"❌ Error: {e}")
        if conn:
            conn.rollback()
    finally:
        if conn:
            cursor.close()
            conn.close()
            print("\n🔒 Database connection closed")


if __name__ == "__main__":
    print("🚀 Fake Candidate Data Generator")
    print("=" * 50)
    print(f"Target: Generate 100 fake candidates")
    print("=" * 50)

    populate_database(100)

    print("\n✨ Done!")
